version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    container_name: ecommerce_app_db
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: ecommerce_app_drf
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/
      - dev-static-data:/vol/web
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=admin
      - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - celery
      - rabbitmq

  # Elasticsearch
  search:
    container_name: ecommerce_elasticsearch
    image: elasticsearch:7.17.9
    environment:
      - cluster.name=ecommerce-elasticsearch
      - discovery.type=single-node
    ports:
      - "9200:9200"
    depends_on:
      - db

  # Celery worker
  celery:
    build: .
    container_name: ecommerce_celery
    command: celery -A e_commerce worker -l info
    volumes:
      - .:/app/
    depends_on:
      - rabbitmq

  # RabbitMQ
  rabbitmq:
    container_name: ecommerce_rabbitmq
    image: rabbitmq:3.11.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  # Redis
  redis:
    image: redis:7.0
    container_name: ecommerce_redis
    ports:
      - "6379:6379"

volumes:
  dev-db-data:
  dev-static-data: