# Generated by Django 4.1.7 on 2023-03-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='unique product code'),
        ),
    ]
